### ISSUE TITLE
[Feature] Encryption Command Line Switch

### ISSUE THREAD

**Issue by am0nsec** [TheWover/donut#23]
Good morning/evening everyone;

As discusses with @TheWover yesterday, a command line switch for enabling/disabling shellcode encryption would be a good idea.

At the moment, the shellcode is encrypted solely if the "NOCRYPTO" flag is **not** set during the compilation of the program. In order to have something more *flexible* a command line switch would be much better.

My idea is to add a global integer variable in the `donut.h` header file, which will by default set to `0`.
```c
in ENCRYPT_SHELLCODE = 0
```

Then modify all the `#if !defined(NOCRYPTO)` directive for an if statement. For example:
```c
#if !defined(NOCRYPTO)
    DPRINT("Generating random key for instance");
    if(!CreateRandom(&inst_key, sizeof(DONUT_CRYPT))) {
      return DONUT_ERROR_RANDOM;
    }
    memcpy(&inst->key, &inst_key, sizeof(DONUT_CRYPT));
    
    DPRINT("Generating random key for module");
    if(!CreateRandom(&mod_key, sizeof(DONUT_CRYPT))) {
      return DONUT_ERROR_RANDOM;
    }
    memcpy(&inst->mod_key, &mod_key, sizeof(DONUT_CRYPT));
    
    DPRINT("Generating random string to verify decryption");
    if(!GenRandomString(inst->sig, DONUT_SIG_LEN)) {
      return DONUT_ERROR_RANDOM;
    }
   
    DPRINT("Generating random IV for Maru hash");
    if(!CreateRandom(&inst->iv, MARU_IV_LEN)) {
      return DONUT_ERROR_RANDOM;
    }
#endif
```

Will be modified into this:
```c
if (ENCRYPT_SHELLCODE) {
DPRINT("Generating random key for instance");
    if(!CreateRandom(&inst_key, sizeof(DONUT_CRYPT))) {
      return DONUT_ERROR_RANDOM;
    }
    memcpy(&inst->key, &inst_key, sizeof(DONUT_CRYPT));
    
    DPRINT("Generating random key for module");
    if(!CreateRandom(&mod_key, sizeof(DONUT_CRYPT))) {
      return DONUT_ERROR_RANDOM;
    }
    memcpy(&inst->mod_key, &mod_key, sizeof(DONUT_CRYPT));
    
    DPRINT("Generating random string to verify decryption");
    if(!GenRandomString(inst->sig, DONUT_SIG_LEN)) {
      return DONUT_ERROR_RANDOM;
    }
   
    DPRINT("Generating random IV for Maru hash");
    if(!CreateRandom(&inst->iv, MARU_IV_LEN)) {
      return DONUT_ERROR_RANDOM;
    }
}
```

More than happy to work on this if you think that it is worth it.

Cheers,
Paul.

**Comment by TheWover** [comment]
Some initial notes.

1) Good idea. This would save headache both in dev time and as a user.
2) For options like that, rather than global variables, we use a variable in the DONUT_CONFIG struct that is passed around. That is what is passed into the loader with the user-supplied options.
3) Currently, we allocate some new, writable memory to decrypt the module into before execution. If crypto/compression is disabled, then we should execute the PIC directly without first copying it to a new location. That way, the shellcode will be ACG-compatatble (Arbitrary Code Guard) because it never uses RWX memory or changes RW memory to RX. It would also let the entire PIC execute in RX memory, but comes with the tradeoff of no compression/crypto.

**Comment by am0nsec** [comment]
The reason behind the global variable is because a module like `http_client.c` is using the `NOCRYPTO` directive and do not use the `DONUT_CONFIG` structure.

Example: https://github.com/TheWover/donut/blob/master/loader/http_client.c#L173

Therefore, this would be easier to create a global variable rather than passing the `DONUT_CONFIG` structure to the `DownloadModule` function.

**Comment by TheWover** [comment]
Ahh, gotcha. So the issue is: any variable provided by the user into code that resides in `donut.c` will not carry over into the logic in the loader unless it is passed in through DONUT_CONFIG. We could add a parameter to `DownloadModule` that specifies whether to use encryption. And then have `loader` pass in that true/false from the INSTANCE.

DONUT_CONFIG is what is used to assemble the DONUT_INSTANCE, which is combined with the PIC of the loader. This is because `donut.c` uses a pre-compiled version of the loader to assemble the final PIC. So... compile `loader` -> use exe2h to extract the machine code from `.text` in `loader` and produce `loader_exe_x64.h` and `loader_exe_x86.h` -> `donut.c` uses those x86 and x64 char arrays to construct the final PIC -> `donut.c` combines the filled-out DONUT_INSTANCE struct with the pre-compiled `loader` -> inside of the INSTANCE is a reference to the Module, which is the payload.

**Comment by odzhan** [comment]
A switch to disable encryption can be added, although I'm not sure how it would make the code more _flexible_. I'm assuming you want encryption disabled so the shellcode can run multiple modules, because at the moment, the shellcode can only decrypt a module it was generated with. 

A solution to this is using public key encryption. For example,  we can generate an RSA key pair. The private key is used to encrypt a symmetric key that is then stored inside the module.The shellcode downloads the module, decrypts the symmetric key using the public key and then decrypts the file itself before executing.

That way, multiple modules can be supported and encryption can still be used without compromising the module itself.

**Comment by TheWover** [comment]
I believe he was asking for this so that the user can specify at will (or users of the API can specify dynamically) whether to use encryption without re-compiling. It would also help the people who are converting `donut.c` to other languages because they could more easily diff their output with ours.

When making this change, I think that (when we are not decrypting) we should also not perform any writes to memory. So, don't allocate new memory and copy the payload. Just run it from the location it is already located at in memory. That way, we never need to use any writable memory. The side effect of this is that we will be able to run in processes with Arbitrary Code Guard enabled.

We could have a command-line switch with three options: 1) Compress and encrypt the payload. 2) Compress the payload. 3) Encrypt the payload. 4) Do not compress or encrypt the payload.

Does that make sense @odzhan ? We can discuss this for a bit, because I know that this would require changing a fair amount of code.

**Comment by odzhan** [comment]
Yes, that makes sense.

**Comment by odzhan** [comment]
Paul @am0nsec

I've updated the switches (mentioned in previous issue) although they will likely be updated again to be less confusing. Now, -f is used to specify format and -e is used as an entropy switch. The entropy levels are 1=disable, 2=use random names, 3=random names + symmetric encryption (default). Leaving this open for now as the code hasn't been tested much and would like to hear your feedback. Hope this helps!

**Comment by odzhan** [comment]
Will close this for now, but if you need to reopen, feel free.
