### ISSUE TITLE
Incompatible with authentication on web server

### ISSUE THREAD

**Issue by asaurusrex** [TheWover/donut#32]
Just wondering if we can make a version of donut that can authenticate to a webserver to grab the specified payload, currently this capability does not exist

**Comment by odzhan** [comment]
It could be implemented using INTERNET_OPTION_USERNAME and INTERNET_OPTION_PASSWORD flags for InternetSetOption. What setup do you have? What server are you using to host the module?

**Comment by TheWover** [comment]
Will add this for v0.9.3. I can assign this one to myself. I will use this server for testing: https://github.com/http-party/http-server

**Comment by TheWover** [comment]
Received a request to allow for complete compatibility with WebDav, which can use either HTTP Basic Auth or Digest Auth. It can also be configured to use NTLM/Kerberos authentication. Wininet supports all of the above, I think: https://docs.microsoft.com/en-us/windows/win32/wininet/handling-authentication

To start with, will just add support for Basic Auth. If adding support for the others does not add too much complexity, will add them too.

**Comment by odzhan** [comment]
The parsing now supports short or long options like -e or --entropy. This will need plenty of testing, but just as an example, there's --user: option that stores string in auth buffer of DONUT_CONFIG...change to whatever you like. --auth maybe? Whatever user provides will still need to be split before passing to InternetSetOption in http_client.c. I'm assuming WinInet handles authentication once it has a username/password set.

**Comment by odzhan** [comment]
As it turns out, [InternetCrackUrl](https://docs.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetcrackurla) already supports separating username and password in URL. 

[This commit](https://github.com/TheWover/donut/commit/7194eab9664c7513bf01869f34c17e6fb3d4cc33) should support authentication when the URL contains username and password.

Example: https://username:password@192.168.0.1/

If you still have problems with this, feel free to reopen the issue.

**Comment by TheWover** [comment]
Nice! I added that format to the readme and help message
