### ISSUE TITLE
Does not work with cygwin compiled binaries

### ISSUE THREAD

**Issue by CaledoniaProject** [TheWover/donut#37]
I'm trying to run a cygwin compiled binary in memory. According to the document, only PE with relocation table is supported, so I compiled the binary with .reloc section (required binutils 2.34):

main.c

```c
#include <stdio.h>

int main (int argc, char **argv)
{
    FILE *fp = fopen("works.txt", "w+");
    if (fp)
    {
    	fprintf(fp, "It worked!\n");
    	fclose(fp);
    }
    else
    {
    	perror("fopen");
    }
    
    return 0;
}
```

Compile it when reloc table:

```
gcc main.c -o /cygdrive/c/main.exe -Wl,--enable-reloc-section
```

Confirm the binary file runs, and `works.txt` is generated in CWD.

```
c:\donut-master>c:\main.exe
c:\donut-master>type works.txt
It worked!
```

Then I execute the following commands for debugging purpose:

```
c:\donut-master>donut main.exe
c:\donut-master>loader instance
```

No `works.txt` created, so donut does not work with cygwin compiled binaries.

### Logs

1. [donut.txt](https://github.com/TheWover/donut/files/4148159/donut.txt)
2. [loader.txt](https://github.com/TheWover/donut/files/4148161/loader.txt)
3. [cygwin.dll and main.exe](https://github.com/TheWover/donut/files/4148169/upload.zip)

**Comment by odzhan** [comment]
Can you upload the binary here?

**Comment by odzhan** [comment]
Had a quick look in a debugger and if I had a guess, it's related to GetModuleHandle called by cygwin1.dll during initialization. It passes a NULL pointer, assuming the host process is a cygwin compiled binary. This call returns the base address of loader.exe instead of main.exe that's loaded in memory. Initialization routines then attempt to perform some operation that fails and it isn't handled properly, thus crashing the loader or host process running the shellcode.

This is a similar problem to mixed .NET assemblies and while it probably can be patched or hooked in some way to return the base address of the EXE or DLL being executed in memory, the Donut loader doesn't support this.

The dependency on cygwin1.dll, which isn't installed by default on Windows, means it would need to be written to disk otherwise you need some additional code to manually map it into the PEB module list. Manually mapping a DLL into the PEB is doable and I have some code for this. Changing the base address of loader.exe in PEB is possible too, but I haven't tested any of it with Donut.

**Comment by CaledoniaProject** [comment]
Yes, I copied cygwin1.dll to system32 folder.

**Comment by awgh** [comment]
@CaledoniaProject  - Try compiling your program with the MinGW compiler rather than with cygwin.  The MinGW compiler does not require the compatibility layer cygwin1.dll, but can compile anything that cygwin can.

**Comment by CaledoniaProject** [comment]
@awgh Just tried MinGW compiler, it does work for simple programs like the one provided above.

But It does not provide many headers like [sys/ioctl.h](https://github.com/msys2/MINGW-packages/issues/3798), I can't compile the real program in use.

**Comment by TheWover** [comment]
Labeled as `wontfix` for now. A note in the Readme explains that it is not currently supported.

**Comment by TheWover** [comment]
We can reconsider it after v0.9.3 if we believe that it is worth the effort.
