### ISSUE TITLE
Donut does not take -r (CLR runtime version) into consideration

### ISSUE THREAD

**Issue by decardcain603** [TheWover/donut#46]
**OS**
Win7 Enterprise x64
**.NET Framework version**
v3.5
**Command line used**
donut.exe -r v2.0.50727 -c Program -m Main -o out.bin create_temp_file.exe

Expected behavior: shellcode generated is using the v2 CLR 
Possibly actual behavior: -r flag is being ignored, shellcode does not work on target machine

**Comment by TheWover** [comment]
Will attempt to reproduce. If a bug is found, it will be addressed for v0.9.3 final release.

**Comment by odzhan** [comment]
What might be happening: CLRCreateInstance isn't resolving because that was only available in version 4 and it isn't installed. As a result, CorBindToRuntime is invoked requesting ANY version, which by default probably uses v3.5

The reason we didn't allow specifying the version to use with CorBindToRuntime is because if the version isn't available, the CLR will display a message to the user that it failed to load. This then requires interaction from the user. 

![failure_win7](https://user-images.githubusercontent.com/19677456/77488375-f1a59b00-6e2c-11ea-9576-b372000cd5bf.png)

That's probably not the kind of behavior most people using Donut want. :) However, we might be able add an option to work around this. If you tell us how you think it should behave, we can decide then what to do about it.

**Comment by TheWover** [comment]
Thinking about this. I agree with odzhan that we and most users do not want that popup. There are a couple of ways to resolve this:
1) Document the fact that the `-r` flag only works if v4 or later is installed.
2) Just remove the `-r` flag and document that Donut will attempt to use whatever the latest version of .NET is. Not ideal because it removes some choice from the user, but it is most reliable behavior for the loader.
