### ISSUE TITLE
Additions to Donut >= v0.9.3 (feedback welcome)

### ISSUE THREAD

**Issue by odzhan** [TheWover/donut#7]
- Option to encode shellcode with base64.
Some users may encode payload before using with a .NET tool for process injection. Would users want the option of encoding the shellcode before saving to disk?

- Option to specify behaviour of connections over HTTPS.
Currently, donut ignores invalid certificates over HTTPS, but that may not be desirable. Should an option that allow users to specify be added?

**Comment by bit-St0rm** [comment]
+1 for option of base64 encoded shellcode.

**Comment by aus** [comment]
Option to customize the module name for staged shellcode from command line

**Comment by phra** [comment]
is it possible to add arguments passing also for normal EXEs?

**Comment by odzhan** [comment]
At the moment, only DLL functions can accept arguments, but it will be added to next version.

**Comment by odzhan** [comment]
@phra I added some code to update the command line for EXE files. It's not complete -- It doesn't save and restore the original command line. Worked for Ansi and Unicode versions of a test program that accepts console input, but didn't work for mimikatz. Check out SetCommandLineW in the latest dev version and let me know what you think.

**Comment by antonioCoco** [comment]
> @phra I added some code to update the command line for EXE files. It's not complete -- It doesn't save and restore the original command line. Worked for Ansi and Unicode versions of a test program that accepts console input, but didn't work for mimikatz. Check out SetCommandLineW in the latest dev version and let me know what you think.

Hi @odzhan ,
my congratulations for this great project! :)

I made some tests with the commit dafbdbd and tried out the SetCommandLineW debugging with payload.exe API.

I used this code as unmanaged EXE test:

```
int wmain (int argc, wchar_t **argv)
{
    wprintf(L"\nHello from WMAIN\n");
    wprintf(L"\nArgc: %d\n", argc);
    wprintf(L"\nArgv0: %s\n", argv[0]);
    wprintf(L"\nArgv1: %s\n", argv[1]);
    return 0;
}
```

The problem i see in changing the PEB commandline field is that it affects only calls to GetCommandLineW() and not if a programm access argv[] (like mimikatz).
So, the above program crash because it can't find the appropriate indexes.

As a side note the argc,argv parameters inherits from the current process. With that in mind i found a possible workaround.

When you call your host process, i.e. notepad.exe, and you inject your mimikatz.bin into it, your mimikatz payload will inherit the same argv as notepad.exe.
This means if you launch your host process with "notepad.exe coffee exit" your mimikatz payload will run the argv commands "coffee exit".

Hope this can help! :)

**Comment by phra** [comment]
atm it seems not possible to pass arguments to .NET exe either. (tested with sharphound)

**Comment by odzhan** [comment]
@antonioCoco Haven't solved the command line problem, yet. Thanks for the feedback! @phra Haven't tested with sharphound. What parameters does it receive?

**Comment by antonioCoco** [comment]
@odzhan 
[@stefano118](https://github.com/stefano118) and i have found a nice way to change the argv parameters and commandline without touching the PEB. We have placed some hooks on the function that manages that variables. (__getmainargs, __p___argv and GetCommandLine). 
We have tested it with mimikatz binary on x64 and x86 windows 10 and everything is working as expected.
You can check changes here 98d1bc40b3764ace5bf239e7856dd9a4bd41c885

Big refactor of the code is ongoing. Once we are done we will submit a PR. :)

**Comment by odzhan** [comment]
SetCommandLineW does work with the code you posted. ![commandline](https://user-images.githubusercontent.com/19677456/66716518-6aa4bf00-edc6-11e9-914a-194629ff87e5.png)

**Comment by phra** [comment]
> SetCommandLineW does work with the code you posted.

shouldn't `argc` be 2 instead of 3?

**Comment by odzhan** [comment]
Here's the program running normally and donut building the shellcode for it.
![first_cmdline](https://user-images.githubusercontent.com/19677456/66716790-da687900-edc9-11e9-9ce4-f16d4598345d.png)

This is the payload being debugged.
![second_cmdine](https://user-images.githubusercontent.com/19677456/66716798-f1a76680-edc9-11e9-9b19-cebdee76538d.png)

Hooking GetCommandLineA and GetCommandLineW is a good idea and perhaps that's what we should use instead of updating the data section. The PEB doesn't necessarily need tot be changed, just the two variables in the data section.

**Comment by antonioCoco** [comment]
> SetCommandLineW does work with the code you posted. ![commandline](https://user-images.githubusercontent.com/19677456/66716518-6aa4bf00-edc6-11e9-914a-194629ff87e5.png)

this will work only if you compile the test program with modern version of cl.exe
If you try to compile with mingw it won't work.
This because modern version of cl.exe (if i remember correctly starting from 2017) will use the function __p__argv to parse the argv that will read from PEB.
Previous version of cl.exe and current versions of mingw will use the classic function __get_mainargs that won't parse data from PEB

**Comment by phra** [comment]
> Here's the program running normally and donut building the shellcode for it.
arg2 was not visible in the previous screenshot. now it makes sense.

> was already planning to hook ExitProcess for EXE files
in case make it configurable since it can be useful when injecting pre-existing processes but not so much when injecting into new, dedicated, spawned processes where having it automatically exiting at the end saves you from doing manual clean up.

**Comment by antonioCoco** [comment]
Using this as an example code:

```
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <wchar.h>

int main (int argc, char **argv)
{
    printf("\nHello from ANSI MAIN\n");
    printf("\nArgc: %d\n", argc);
    for(DWORD i=0; i<argc; i++)
        printf("\nArgv[%d]: %s\n", i, argv[i]);
    char *wcommandline = GetCommandLineA();
    printf("\nGetCommandLineA(): %s\n", wcommandline);
    printf("\nANSI MAIN End. BB!\n");
    return 0;
}
```

This is what happens if you compile it with mingw:

![image](https://user-images.githubusercontent.com/19797064/66717534-8619c500-edda-11e9-9337-d2b75e156e40.png)

The changes to commandline doesnt affect argv.

**Comment by odzhan** [comment]
Well, it should affect argv :) ...but I can see now mingw is using msvcrt!_wcmdln for wmain() and msvcrt!_acmdln for main(). The good news is that these two symbols are exported by msvcrt, so changing the pointers are enough in this case. So, while changing BaseUnicodeCommandLine, the same pointer can be used roughly like this:

``      wchar_t **_wcmdln = (wchar_t**)inst->api.GetProcAddress(inst->api.GetModuleHandle("msvcrt"), "_wcmdln");
      
      _wcmdln[0] = wcs->Buffer;``

**Comment by antonioCoco** [comment]
> 
> 
> Well, it should affect argv :) ...but I can see now mingw is using msvcrt!_wcmdln for wmain() and msvcrt!_acmdln for main(). The good news is that these two symbols are exported by msvcrt, so changing the pointers are enough in this case. So, while changing BaseUnicodeCommandLine, the same pointer can be used roughly like this:
> 
> `wchar_t **_wcmdln = (wchar_t**)inst->api.GetProcAddress(inst->api.GetModuleHandle("msvcrt"), "_wcmdln"); _wcmdln[0] = wcs->Buffer;`

Great! This fixed also mimikatz argv (tested).
Which of the 2 approaches is ideal in your opinion? Hooking functions or patching data section ?

**Comment by odzhan** [comment]
Both are good. The reason I chose to modify data for _acmdln+_wcmdln is just because it was quicker to implement with the existing SetCommandLineW code. BaseDllInitialize that sets BaseUnicodeCommandLine and BaseAnsiCommandLine has been part of windows for 30+ years, so we can safely assume the variables exist in either kernel32.dll or kernelbase.dll for all past and present versions of windows.  I've no idea if changing code is more difficult to detect than changing data. 

On the other hand, hooking GetCommandLineA/GetCommandLineW and __getmainargs/__wgetmainargs might be easier to implement so long as a pointer to the instance can be accessed when required. How did you solve this? Perhaps storing the pointer somewhere in the PEB?. 

The hook I was considering for ExitProcess would just call ExitThread. Currently, the IAT is patched, but this is unreliable and needs updating, so I think an empty slot in the PEB for all versions of windows would be useful to implement hooking. Maybe even the data section of a windows DLL could be used to store pointer to an instance too?

**Comment by phra** [comment]
i am trying again sharphound with the latest dev branch, but this version i don't get the output. on the v0.9.2 you can see the usage because the command line is not correctly parsed.

branch dev:
![image](https://user-images.githubusercontent.com/984628/66722569-a0ba6100-ee0f-11e9-81ce-e6b9ea732a09.png)


v0.9.2:
![image](https://user-images.githubusercontent.com/984628/66722570-a748d880-ee0f-11e9-94d7-daeec8d1a2d0.png)

**Comment by odzhan** [comment]
For now, place the name of application in command line first like: -p "sharphound --CollectionMethod All --SearchForest --Threads 20" Will fix this tomorrow.

**Comment by odzhan** [comment]
Try: donut -f sharphound.exe -p --CollectionMethod,All,--SearchForest

**Comment by phra** [comment]
dev branch: (it hangs)
![image](https://user-images.githubusercontent.com/984628/66723958-09a9d500-ee20-11e9-8812-33cb0a63ad66.png)

v0.9.2: (parameters seems ignored)
![image](https://user-images.githubusercontent.com/984628/66724049-24c91480-ee21-11e9-8048-3c6d133eb828.png)

**Comment by phra** [comment]
also i noticed that with .NET exe the injected process is not exiting as with regular exe.. is there anything converting the `ExitProcess` into `ExitThread` in the .NET version already in place?

**Comment by odzhan** [comment]
I'll update parsing arguments tomorrow. Should have just copied -p argument to be processed with CommandLineToArgvW. If you look at the import table (dumpbin /imports sharphound.exe), you'll see one mscoree!_CorExeMain but internally mscoree!CorExitProcess is resolved dynamically upon exiting the application. The plan is to hook both mscoree!CorExitProcess for managed EXE and ntdll!RtlExitUserProcess for unmanaged EXE so the AppDomain can be unloaded and doesn't leave behind footprint.

**Comment by phra** [comment]
i just suggest leaving the exit behaviour configurable since sometimes exiting the whole process can be wanted behaviour (spawned processes) versus exiting just the thread (existing processes) for all cases.

**Comment by odzhan** [comment]
Yes, there will be an option so the user can specify behaviour.

**Comment by antonioCoco** [comment]
> 
> 
> Both are good. The reason I chose to modify data for _acmdln+_wcmdln is just because it was quicker to implement with the existing SetCommandLineW code. BaseDllInitialize that sets BaseUnicodeCommandLine and BaseAnsiCommandLine has been part of windows for 30+ years, so we can safely assume the variables exist in either kernel32.dll or kernelbase.dll for all past and present versions of windows. I've no idea if changing code is more difficult to detect than changing data.
> 
> On the other hand, hooking GetCommandLineA/GetCommandLineW and __getmainargs/__wgetmainargs might be easier to implement so long as a pointer to the instance can be accessed when required. One negative aspect about patching code is when it comes to calling conventions, architectures. Windows supports three, so maybe patching data has advantage there.
> 
> The hook I was considering for ExitProcess would just call ExitThread. Currently, the IAT is patched, but this is unreliable and needs updating, so I think an empty slot in the PEB for all versions of windows would be useful to implement hooking. Maybe even the data section of a windows DLL could be used to store pointer to an instance too?

The main problem we found in hooking the function was in accesing the donut instance.
From debug build it was possible using global variables but then we noticed that in the release version everything get stripped and the final PIC is only the .text section of payload.exe.
Then we found a big hack for hijacking function pointers and let them point to instance pointer, so it was possible, from the hooked function, to access the instance data through a function pointer.
This hack works well for x64 bit but not for x86 payloads.
Sadly we couldn't find a way to fix the x86 build neither the root cause of why we couldn't use function pointer as integer like in the x64 bit hack.

In the end we choose a more low level approach by defining the asm code of the hooked function and allocating at runtime the memory to run it.
This address then will be the one that will replace the address of the real function.
Having the asm code manipulation is easier to pass pointers from donut instance directly in registers.
Luckily enough the function to be hooked for the commandline hadn't that hard logic so the asm code needed wasn't that trivial to write and debug.

In that way we are able to hook every function we need with the access to donut instance.
Some considerations must be taken... For every hooked function you should define the corresponding asm code and allocate at runtime.
This could be trivial if you need to define hooking function with complex logics, (i.e. rootkit behaviours)

It would be nice to have a reliable way to access instance data from hooked functions without defining the asm code, but just writing the c code within the inmem_pe module but ATM we couldn't find a way to do that if not using asm code.
For sure if the instance pointer can be placed somewhere on PEB at a fixed offset, it could be easily reached from the hooked function and could take away the effort of writing asm code.

Considering that you cannot pass any parameters to hooked functions, i don't think that using the data section af a dll could work because, from the hooked function, you will need the instance itself to find the instance data in the data section .

**Comment by hackabean** [comment]
Hey @odzhan amazing project, thank you for your work. Just wanted to kindly ask for +1 for base64 if possible.

**Comment by odzhan** [comment]
Yes, just added it. Will update dev repo soon.

**Comment by odzhan** [comment]
@phra With the new method of processing command line in dev branch, how does sharphound work for you? donut -f sharphound.exe -p"--CollectionMethod All --SearchForest --Threads 20"

Unfortunately I can't properly test sharphound at the moment.

**Comment by odzhan** [comment]
@hackabean Just in case you didn't see dev branch updated. -e option now encodes shellcode with base64. Also copies to clipboard on windows.

**Comment by hackabean** [comment]
I have just noticed, that's amazing @odzhan many thanks. I am exploring all donut has to offer at the moment and it makes me wonder, can it ever run python binaries compiled with pyinstaller or py2exe ?

**Comment by odzhan** [comment]
@TheWover and myself were talking about supporting python some months ago. Since python isn't installed by default on windows, donut currently doesn't support it. However, we know Microsoft intend to support python in the future. We haven't tested anything generated by py2exe or pyinstaller.

**Comment by hackabean** [comment]
No worries, project like that just makes you wonder about the possibilities. Thanks for answering and have a great day/night.

**Comment by phra** [comment]
@odzhan i have tried with mimikatz and the command line is somehow corrupted:

command:
`donut -f /opt/mimikatz/x64/mimikatz.exe -a 2 -o /opt/mimikatz/x64/mimicmd.bin -p "log base64 coffee exit"`

output:
```
msf5 post(windows/manage/shellcode_inject) > run

[*] Running module against CWPWindows
[*] Spawned process 6256
[*] Process found checking Architecture
[+] Process is the same architecture as the payload
[*] Injecting shellcode into process ID 6256
[*] Allocating memory in process 6256
[*] Allocated memory at address 0x1c035f00000, for 1027931 byte shellcode
[+] Successfully injected payload into process: 6256
[*] Interacting

  .#####.   mimikatz 2.2.0 (x64) #18362 Aug 14 2019 01:31:47
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > http://pingcastle.com / http://mysmartlogon.com   ***/

mimikatz(commandline) # base64
isBase64InterceptInput  is false
isBase64InterceptOutput is false
[*] Post module execution completed
```

**Comment by odzhan** [comment]
For unmanaged EXE files, a random 4 byte string is added. 

![mimikatz_donut](https://user-images.githubusercontent.com/19677456/67022909-de620700-f0f9-11e9-98ba-de318b029f7d.png)

![mimikatz_running](https://user-images.githubusercontent.com/19677456/67022922-e1f58e00-f0f9-11e9-82bf-1af0b98eff3b.png)
